title: Joseph Regan Hutson
description: > # this means to ignore newlines until "baseurl:"
  Portfolio site for Joseph Regan Hutson. 
  Python developer focused on using data to answer critical questions. 
  Analysis performed using Pandas, Geopandas and QGIS.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Joseph Regan Hutson # add your name
author-img: DuckThumbnail.png # add your photo
about-author: Python Developer focused on Data Analysis and Automation  # add description
social-twitter: JRHutson# add your Twitter handle
social-facebook: # add your Facebook handle
social-github: JRHutson # add your Github handle
social-linkedin: jrhutson # add your Linkedin handle
social-email: hutson.regan@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
